version: "3"

services:
  oracledb:
    image: "gvenzl/oracle-xe:${TAG:-18}"
    container_name: oracledb
    ports:
      - 1521:1521
    env_file:
      - ./oracle.env
    volumes:
      - oracledb-volume:/u01/app/oracle/oradata

volumes:
  oracledb-volume:
